function myFunction() {
    document.getElementById("demo").innerHTML = "O universo (que outros chamam a Biblioteca) compõe-se de um número indefinido, e talvez infinito, de galerias hexagonais, com vastos poços de ventilação no centro, cercados por balaustradas baixíssimas. De qualquer hexágono, vêem-se os andares inferiores e superiores: interminavelmente. A distribuição das galerias é invariável. Vinte prateleiras, em cinco longas estantes de cada lado, cobrem todos os lados menos dois; sua altura, que é a dos andares, excede apenas a de um bibliotecário normal";
}

function myFunction1() {
    document.getElementById("demo1").innerHTML = "Uma das faces livres dá para um estreito vestíbulo, que desemboca em outra galeria, idêntica à primeira e a todas. A esquerda e à direita do vestíbulo, há dois sanitários minúsculos. Um permite dormir em pé; outro, satisfazer as necessidades físicas. Por aí passa a escada espiral, que se abisma e se eleva ao infinito. No vestíbulo há um espelho, que fielmente duplica as aparências. Os homens costumam inferir desse espelho que a Biblioteca não é infinita (se o fosse realmente, para que essa duplicação ilusória?), prefiro sonhar que as superfícies polidas representam e prometem o infinito... A luz procede de algumas frutas esféricas que levam o nome de lâmpadas. Há duas em cada hexágono: transversais. A luz que emitem é insuficiente, incessante.";
}
function myFunction2() {
    document.getElementById("demo2").innerHTML = "Como todos os homens da Biblioteca, viajei na minha juventude; peregrinei em busca de um livro, talvez do catálogo de catálogos; agora que meus olhos quase não podem decifrar o que escrevo, preparo-me para morrer, a poucas léguas do hexágono em que nasci. Morto, não faltarão mãos piedosas que me joguem pela balaustrada; minha sepultura será o ar insondável; meu corpo cairá demoradamente e se corromperá e dissolverá no vento gerado pela queda, que é infinita. Afirmo que a Biblioteca é interminável. Os idealistas argúem que as salas hexagonais são uma forma necessária do espaço absoluto ou, pelo menos, de nossa intuição do espaço";
}


function myFunction3() {
    document.getElementById("demo3").innerHTML = "Alegam que é inconcebível uma sala triangular ou pentagonal. (Os místicos pretendem que o êxtase lhes revele uma câmara circular com um grande livro circular de lombada contínua, que siga toda a volta das paredes; mas seu testemunho é suspeito; suas palavras, obscuras. Esse livro cíclico é Deus.) Basta-me, por ora, repetir o preceito clássico: ´A Biblioteca é uma esfera cujo centro cabal é qualquer hexágono, cuja circunferência é inacessível`.";
}


function myFunction4() {
    document.getElementById("demo4").innerHTML = "A cada um dos muros de cada hexágono correspondem cinco estantes; cada estante encerra trinta e dois livros de formato uniforme; cada livro é de quatrocentas e dez páginas; cada página, de quarenta linhas; cada linha, de umas oitenta letras de cor preta. Também há letras no dorso de cada livro; essas letras não indicam ou prefiguram o que dirão as páginas. Sei que essa inconexão, certa vez, pareceu misteriosa. Antes de resumir a solução (cuja descoberta, apesar de suas trágicas projeções, é talvez o fato capital da história); quero rememorar alguns axiomas.";
}

function myFunction5() {
    document.getElementById("demo5").innerHTML = "O primeiro: A Biblioteca existe ab aeterno. Dessa verdade cujo corolário imediato é a eternidade futura do mundo, nenhuma mente razoável pode duvidar. O homem, o imperfeito bibliotecário, pode ser obra do acaso ou dos demiurgos malévolos; o universo, com seu elegante provimento de prateleiras, de tomos enigmáticos, de infatigáveis escadas para o viajante e de latrinas para o bibliotecário sentado, somente pode ser obra de um deus. Para perceber a distância que há entre o divino e o humano, basta comparar esses rudes símbolos trêmulos que minha falível mão garatuja na capa de um livro, com as letras orgânicas do interior: pontuais, delicadas, negríssimas, inimitavelmente simétrica.";
}

function myFunction6() {
    document.getElementById("demo6").innerHTML = "O segundo: <ins>O número de símbolos ortográficos é vinte e cinco.<sup>1</sup></ins> Essa comprovação permitiu, depois de trezentos anos, formular uma teoria geral da Biblioteca e resolver satisfatoriamente o problema que nenhuma conjetura decifrara: a natureza disforme e caótica de quase todos os livros. Um, que meu pai viu em um hexágono do circuito quinze noventa e quatro, constava das letras M C V perversamente repetidas da primeira linha até a última. Outro (muito consultado nesta área) é um simples labirinto de letras, mas a página penúltima diz “Oh, tempo tuas pirâmides”. Já se sabe: para uma linha razoável ou uma correta informação, há léguas de insensatas cacofonias, de confusões verbais e de incoerências. (Sei de uma região montanhosa cujos bibliotecários repudiam o supersticioso e vão costume de procurar sentido nos livros e o equiparam ao de procurá-lo nos sonhos ou nas linhas caóticas da mão... Admitem que os inventores da escrita imitaram os vinte e cinco símbolos naturais, mas sustentam que essa aplicação é casual, e que os livros em si nada significam. Esse ditame, já veremos, não é completamente falaz.)";
}
function myFunction14() {
    
    document.getElementById("demo19").innerHTML =                    "1-O manuscrito original não contém algarismos ou maiúsculas. A pontuação foi limitada à vírgula e aoponto. Esses dois signos, o espaço e as vinte e duas letras do alfabeto são os vinte e cinco símbolos suficientes que enumera o desconhecido. (Nota do Editor.).";
}

function myFunction7() {
    document.getElementById("demo7").innerHTML =  "Há quinhentos anos,<ins> o chefe de um hexágono superio <sup>2</sup></ins>deparou com um livro tão confuso como os outros, porém que possuía quase duas folhas de linhas homogêneas. Mostrou seu achado a um decifrador ambulante, que lhe disse que estavam redigidas em português; outros lhe afirmaram que em iídiche. Antes de um século pôde ser estabelecido o idioma: um dialeto samoiedo-lituano do guarani, com inflexões de árabe clássico. Também decifrou-se o conteúdo: noções de análise combinatória, ilustradas por exemplos de variantes com repetição ilimitada. Esses exemplos permitiram que um bibliotecário de gênio descobrisse a lei fundamental da Biblioteca. Esse pensador observou que todos os livros, por diversos que sejam, constam de elementos iguais: o espaço, o ponto, a vírgula, as vinte e duas letras do alfabeto. Também alegou um fato que todos os viajantes confirmaram: ´Não há, na vasta Biblioteca, dois livros idênticos`";
     document.getElementById("demo8").innerHTML =  "Durante muito tempo, acreditou-se que esses livros impenetráveis correspondiam a línguas pretéritas ou remotas. É verdade que os homens mais antigos, os primeiros bibliotecários, usavam uma linguagem assaz diferente da que falamos agora; é verdade que algumas milhas à direita a língua é dialetal e que noventa andares mais acima é incompreensível. Tudo isso, repito-o, é verdade, mas quatrocentas e dez páginas de inalteráveis M C V não podem corresponder a nenhum idioma, por dialetal ou rudimentar que seja. Uns insinuaram que cada letra podia influir na subseqüente e que o valor de M C V na terceira linha da página 71 não era o que pode ter a mesma série noutra posição de outra página, mas essa vaga tese não prosperou. Outros pensaram em criptografias; universalmente essa conjetura foi aceita, ainda que não no sentido em que a formularam seus inventores.";
      document.getElementById("demo9").innerHTML =  " Dessas premissas incontrovertíveis deduziu que a Biblioteca é total e que suas prateleiras registram todas as possíveis combinações dos vinte e tantos símbolos ortográficos (número, ainda que vastíssimo, não infinito), ou seja, tudo o que é dado expressar: em todos os idiomas. Tudo: a história minuciosa do futuro, as autobiografias dos arcanjos, o catálogo fiel da Biblioteca, milhares e milhares de catálogos falsos, a demonstração da falácia desses catálogos, a demonstração da falácia do catálogo verdadeiro, o evangelho gnóstico de Basilides, o comentário desse evangelho, o comentário do comentário desse evangelho, o relato verídico de tua morte, a versão de cada livro em todas as línguas, as interpolações de cada livro em todos os livros; o tratado que Beda pôde escrever (e não escreveu) sobre a mitologia dos saxões, os livros perdidos de Tácito.";
}


function myFunction8() {
    document.getElementById("demo10").innerHTML =  "Também se esperou então o esclarecimento dos mistérios básicos da humanidade: a origem da Biblioteca e do tempo. É verossímil que esses graves mistérios possam explicar- se em palavras: se não bastar a linguagem dos filósofos, a multiforme Biblioteca produzirá o idioma inaudito que se requer e os vocabulários e gramáticas desse idioma. Faz já quatro séculos que os homens esgotam os hexágonos... Existem investigadores oficiais, inquisidores. Eu os vi no desempenho de sua função: chegam sempre estafados; falam de uma escada sem degraus que quase os matou; falam de galerias e de escadas com o bibliotecário; às vezes, pegam o livro mais próximo e o folheiam, à procura de palavras infames. Visivelmente, ninguém espera descobrir nada.";
     document.getElementById("demo11").innerHTML =  " À desmedida esperança, sucedeu, como é natural, uma depressão excessiva. A certeza de que alguma prateleira em algum hexágono encerrava livros preciosos e de que esses livros preciosos eram inacessíveis afigurou-se quase intolerável. Uma seita blasfema sugeriu que cessassem as buscas e que todos os homens misturassem letras e símbolos, até construir, mediante um improvável dom do acaso, esses livros canônicos. As autoridades viram-se obrigadas a promulgar ordens severas. A seita desapareceu, mas na minha infância vi homens velhos que demoradamente se ocultavam nas latrinas, com alguns discos de metal num fritilo proibido, e debilmente arremedavam a divina desordem.";
}

function myFunction9() {
    document.getElementById("demo12").innerHTML = " Outros, inversamente, acreditaram que o primordial era eliminar as obras inúteis. Invadiam os hexágonos, exibiam credenciais nem sempre falsas, folheavam com fastio um volume e condenavam prateleiras inteiras: a seu furor higiênico, ascético, deve-se a insensata perda de milhões de livros. Seu nome é execrado, mas aqueles que deploram os ´tesouros`destruídos por seu frenesi negligenciam dois fatos notórios. Um: a Biblioteca é tão imensa que toda redução de origem humana resulta infinitesimal. Outro: cada exemplar é único, insubstituível, mas (como a Biblioteca é total) há sempre várias centenas de milhares de fac-símiles imperfeitos: de obras que apenas diferem por uma letra ou por uma vírgula. Contra a opinião geral, atrevo-me a supor que as conseqüências das depredações cometidas pelos Purificadores foram exageradas graças ao horror que esses fanáticos provocaram. Urgia-lhes o delírio de conquistar os livros do Hexágono Carmesim: livros de formato menor que os naturais; onipotentes, ilustrados e mágicos.";
}




function myFunction10() {
    document.getElementById("demo13").innerHTML =  "Também sabemos de outra superstição daquele tempo: a do Homem do Livro. Emalguma estante de algum hexágono (raciocinaram os homens) deve existir um livro que seja a cifra e o compêndio perfeito de todos os demais: algum bibliotecário o consultou e é análogo a um deus. Na linguagem desta área persistem ainda vestígios do culto desse funcionário remoto. Muitos peregrinaram à procura de Ele. Durante um século trilharam em vão os mais diversos rumos. Como localizar o venerado hexágono secreto que o hospedava? Alguém propôs um método regressivo: Para localizar o livro A, consultar previamente um livro B, que indique o lugar de A; para localizar o livro B, consultar previamente um livro C, e assim até o infinito... Em aventuras como essas, prodigalizei econsumi meus anos. ";
    
     document.getElementById("demo14").innerHTML =  "Não me parece inverossímil que <ins> em alguma prateleira do universo haja um livro total!<sup>3 </ins> Rogo aos deuses ignorados que um homem – um só, ainda que seja há mil anos! – o tenha examinado e lido. Se a honra e a sabedoria e a felicidade não estão para mim, que sejam para outros. Que o céu exista, embora meu lugar seja o inferno. Que eu seja ultrajado e aniquilado, mas que num instante, num ser, Tua enorme Biblioteca se justifique.Afirmam os ímpios que o disparate é normal na Biblioteca e que o razoável (e mesmo a humilde e pura coerência) é quase milagrosa exceção. Falam (eu o sei) de ´a Biblioteca febril, cujos fortuitos volumes correm o incessante risco de transformar-se em outros e que tudo afirmam, negam e confundem como uma divindade que delira.`";
      document.getElementById("demo15").innerHTML =  " Essas palavras, que não apenas denunciam a desordem mas que também a exemplificam, provam, evidentemente, seu gosto péssimo e sua desesperada ignorância. De fato, a Biblioteca inclui todas as estruturas verbais, todas as variantes que permitem os vinte e cinco símbolos ortográficos, porém nem um único disparate absoluto. Inútil observar que o melhor volume dos muitos hexágonos que administro intitula-se Trovão Penteado, e outro A Cãibra de Gesso e outro Axaxaxas mlö. Essas proposições, à primeira vista incoerentes, sem dúvida são passíveis de uma justificativa criptográfica ou alegórica; essa justificativa é verbal e, ex hypothesi, já figura na Biblioteca. Não posso combinar certos caracteres <m><strong>dhemrlchtdj</strong></m>";
}


function myFunction11() {
    document.getElementById("demo16").innerHTML = " que a divina Biblioteca não tenha previsto e que em alguma de suas línguas secretas não contenham um terrível sentido. Ninguém pode articular uma sílaba que não esteja cheia de ternuras e de temores; que não seja em alguma dessas linguagens o nome poderoso de um deus. Falar é incorrer em tautologias. Esta epístola inútil e palavrosa já existe num dos trinta volumes das cinco prateleiras de um dos incontáveis hexágonos – e também sua refutação. (Um número n de linguagens possíveis usa o mesmo vocabulário; em alguns, o símbolo biblioteca admite a correta definição ubíquo e perdurável sistema de galerias hexagonais, mas biblioteca é pão ou pirâmide ou qualquer outra coisa, e as sete palavras que a definem têm outro valor. Você, que me lê, tem certeza de entender minha linguagem?).";
}


function myFunction12() {
    document.getElementById("demo17").innerHTML = " A escrita metódica distrai-me da presente condição dos homens. A certeza de que tudo está escrito nos anula ou nos fantasmagoriza. Conheço distritos em que os jovens se prostram diante dos livros e beijam com barbárie as páginas, mas não sabem decifrar uma única letra. As epidemias, as discórdias heréticas, as peregrinações que inevitavelmente degeneram em bandoleirismo, dizimaram a população. Acredito ter mencionado os suicídios, cada ano mais freqüentes. Talvez me enganem a velhice e o temor, mas suspeito que a espécie humana – a única – está por extinguir-se e que a Biblioteca perdurará: iluminada, solitária, infinita, perfeitamente imóvel, armada de volumes preciosos, inútil, incorruptível, secreta.";
}


function myFunction13() {
    document.getElementById("demo18").innerHTML = " Acabo de escrever infinita. Não interpolei esse adjetivo por costume retórico; digo que não é ilógico pensar que o mundo é infinito. Aqueles que o julgam limitado postulam que em lugares remotos os corredores e escadas e hexágonos podem inconcebivelmente cessar – o que é absurdo. Aqueles que o imaginam sem limites esquecem que os abrange o número possível de livros. Atrevo-me a insinuar esta solução do antigo problema: A Biblioteca é ilimitada e periódica. Se um eterno viajante a atravessasse em qualquer direção, comprovaria ao fim dos séculos que os mesmos volumes se repetem na mesma desordem (que, reiterada, seria uma ordem: a Ordem). Minha solidão alegra-se com essaelegante esperança.";
}


function myFunction16() {
    
    document.getElementById("demo20").innerHTML =                    "3-Repito-o: basta que um livro seja possível para que exista. Somente está excluído o impossível. Por exemplo: nenhum livro é também uma escada, ainda que, sem dúvida, haja livros que discutem e neguem e demonstrem essa possibilidade e outros cuja estrutura corresponde à de uma escada..";
}

function myFunction17() {
    
    document.getElementById("demo21").innerHTML =                    "2-Antes, em cada três hexágonos havia um homem. O suicídio e as enfermidades pulmonares destruíram essa proporção. Lembrança de indizível melancolia: às vezes, viajei muitas noites por corredores e escadas polidas sem encontrar um único bibliotecário.";
}

